### PR TITLE
Icons improvement

### PR DESCRIPTION
**Pull request by RobertBColton**
Backports the ICO file Josh made for master into stable. Rusky thinks it is an improvement as do I. Also adds the missing icons for extensions and help from the original Nuvola icon pack that are consistent with the icons used by GM8.1. This does **NOT** add the extensions resource frame, or any additional support for it, nor the Manual button either. The purpose is just to keep the tree looking balanced and consistent. The node has to be there for the file readers and writers.

Missing Nuvola Icons

These are also the icons the action library maker used. Except the plus icon was used for add, just like the Mark Overmars one.
Lib Maker

Here is the Mark Overmars Action Library Maker for reference.
Mark Overmars Action Library Maker

Here is GameMaker 8 for reference.
GameMaker 8

### CODE REVIEW

**Comment by JoshDreamland** [comment]
LGTM

Nuvola's readme change is confusing, but that's on them.

**Comment by RobertBColton** [comment]
@JoshDreamland Are you ok that LGM would use the same icon as the "Add" button in the action library maker except for Extensions?

**Comment by JoshDreamland** [comment]
Sounds reasonable, I guess, but I'd also consider [this one](https://commons.wikimedia.org/wiki/File:Nuvola_apps_kcmpci.png), or even [this one](https://commons.wikimedia.org/wiki/File:Nuvola_apps_package_settings.png).

**Comment by RobertBColton** [comment]
You know what the icons I picked are basically exactly the same as GM. The only difference here is that we don't have a white page/file icon behind the 3 tree nodes in our IDE. So you know what, I'm fine with this as it is. Thank you Josh.

**Pull request merged**
