### PR TITLE
Stable

### PR DESCRIPTION
**Pull request by paulkokos**
https://github.com/RobertBColton

### CODE REVIEW

**Comment by RobertBColton** [comment]
@paulkokos These changes actually already exist in master, I backported them from master to create stable.

**Comment by RobertBColton** [comment]
For future reference, I've stickied the topic for the stable branch on the forums. #260 is the latest PR.
http://enigma-dev.org/forums/index.php?topic=2630.0

**Comment by paulkokos** [comment]
ok thanks

**Comment by RobertBColton** [comment]
No problem! :smiley: And stay tuned the new LGM is coming soon.

**Comment by paulkokos** [comment]
ok :)

**Pull request closed without merging**
